services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8085
    ports:
      - "8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  payments:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  inventory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
