services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8085

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  payments:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  inventory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
